env: dev

dev:
    base_url: "https://www.irctc.co.in/nget/train-search"
    browser: "chromium"
    headless: false

prod:
    base_url: "https://www.irctc.co.in/nget/train-search"
    browser: "chrome"
    headless: false